name: 🛰️ Deploy static site to S3

on:
  push:
    branches:
      - main      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install & Build
        run: |
          yarn install      # or yarn
          yarn build    # adjust if your command is different

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION || 'us-east-1' }}

      - name: Sync build/ to S3
        run: |
          aws s3 sync ./build/ s3://skincarebeautyspa.com \
            --delete 

